/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('destyler')['Button']
    Header: typeof import('./components/Header.vue')['default']
    Icon: typeof import('destyler')['Icon']
    InfoRoot: typeof import('destyler')['InfoRoot']
    Link: typeof import('destyler')['Link']
    Logo: typeof import('./components/Logo.vue')['default']
    SelectContent: typeof import('destyler')['SelectContent']
    SelectItem: typeof import('destyler')['SelectItem']
    SelectItemIndicator: typeof import('destyler')['SelectItemIndicator']
    SelectItemText: typeof import('destyler')['SelectItemText']
    SelectPortal: typeof import('destyler')['SelectPortal']
    SelectRoot: typeof import('destyler')['SelectRoot']
    SelectScrollDownButton: typeof import('destyler')['SelectScrollDownButton']
    SelectScrollUpButton: typeof import('destyler')['SelectScrollUpButton']
    SelectTrigger: typeof import('destyler')['SelectTrigger']
    SelectValue: typeof import('destyler')['SelectValue']
    SelectViewport: typeof import('destyler')['SelectViewport']
    Settings: typeof import('./components/Settings.vue')['default']
  }
}
